spring:
  application:
    name: Shopping Mall API

  # PostgreSQL Database 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping_mall
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# 로깅 설정
logging:
  level:
    root: INFO
    com.codeit: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 서버 설정
server:
  port: 8080
